### PR TITLE
Add workflow to promote develop pushes to pull requests for the master branch

### PR DESCRIPTION
**Pull request by shanejearley**
This PR adds a workflow in `.github/workflows/promote.yaml` that helps streamline the promotion of PR-approved develop code to the master branch by creating a PR to merge develop into master. Then GitHub releases would ultimately send changes into production or send changes to where they need to be before our continuous delivery solution handles the rest of the work. Tested with [act cli](https://github.com/nektos/act) and a GitHub PAT. 

Also, we will want to build tests to run in `.github/workflows/pull-request.yaml` as these tests will be part of our check before PRs can be merged. 

I'll add us all for PAT access on the repo so you can use your own locally with workflow files:
```sh
act -s GITHUB_TOKEN=[insert token]
```

This needs a bit more work before merging. Going to make sure the workflow auto-populates our reviewers. Saving as a draft for now.

### CODE REVIEW

**Review by DemogorGod — APPROVED** [review]
This is awesome!

**Review by hawyar — APPROVED** [review]
LGTM

**Comment by shanejearley** [comment]
Haha alright, thank you, guys. So now with a few tweaks to our GitHub org's "consensus-dev" team settings we have "auto-assignment" for these auto-PRs – 3 out of 5 of us will be selected by GitHub to be tagged as reviewers. We also now require at least 1/3 PR approvals and for all required checks (in `pull-request.yaml`) to pass before merging into either the `master` or `develop` branch is allowed.

If you're interested, you should be able to inspect the last few PRs that I have closed to see the evolution of test PRs.

**Comment by shanejearley** [comment]
FYI @thespence7 you're in this "consensus-dev" group and might be randomly selected to review PRs 😱

**Pull request merged**
