### PR TITLE
Create layout with navbar and a sidebar drawer

### PR DESCRIPTION
**Pull request by DemogorGod**
@hawyar, Here is the first pr, I just created a layout with a top navbar and a side drawer with a simple transition

below are some images to show what the navbar and sidebar looks like, ignore the content of the page, that is put there to check if the page content shows with no conflict 

image

image

### CODE REVIEW

**Comment by hawyar** [comment]
- Ignore .DS_Store
- The dark overlay animation that comes a split second before the sidebar causes a flicker when you open and close it.  The animation itself is smooth, it might feel more snappy if you just animate the sidebar.

Thank you

**Comment by shanejearley** [comment]
Nice work! The code looks nice. Theming is spot on so far (that orange is nice on white). Are we planning to stay with Tailwind default font? @DemogorGod @hawyar

**Comment by shanejearley** [comment]
@DemogorGod @hawyar I added us as reviewers in the GitHub top right panel of the PR. We need to do this when we open PRs so we can apply safety locks on the main deployed branches according to our SoC policy and internal GitOps. Not enforced yet, but just to get in the habit before we do.

**Review by shanejearley — APPROVED** [review]
Great work getting this review process started @hawyar. Good code @DemogorGod

**Comment by DemogorGod** [comment]
@shanejearley yeah, I added @hawyar as my reviewer, since you said i should go through him more often. sorry i forgot to include you in it

Thanks for the feed back!!!

**Review by hawyar — APPROVED** [review]

**Review by hawyar — APPROVED** [review]

**Pull request merged**
